### ISSUE TITLE
Create UML diagrams

### ISSUE THREAD

**Issue by TalMekler** [TrafficTune/Traffic_Tune_Project#15]

**Comment by matand380** [comment]
![WhatsApp Image 2024-06-27 at 12 23 40](https://github.com/TrafficTune/Traffic_Tune_Project/assets/73496652/ac24830d-1c56-4e95-852e-0e965a06f1ce)
![WhatsApp Image 2024-06-27 at 12 24 04](https://github.com/TrafficTune/Traffic_Tune_Project/assets/73496652/08d9edee-d26d-4984-a803-81865f0feb47)
