### ISSUE TITLE
Create repo hierarchy

### ISSUE THREAD

**Issue by matand380** [TrafficTune/Traffic_Tune_Project#16]
- Logs
- Outputs
  - Training
  - Prediction
- Models
- Nets
- Config
- Visualizations
  - Graphs
  - Videos
  - Images

**Comment by TalMekler** [comment]
commit [7467600](https://github.com/TrafficTune/Traffic_Tune_Project/commit/7467600bb48ea680b6131f82e917a0b0afbdcd4f)
